-- TRU-145: baseline schema migration.
--
-- The core schema (users, bookings, booking_series, provider/customer profiles,
-- pets, walks, gps, etc.) was created directly in the live DB before the
-- supabase/migrations/ folder existed, so it was never captured as a migration.
-- The Supabase Preview (branch) check replays migrations from scratch on a fresh
-- DB and died on the first migration that referenced these tables.
--
-- This file reconstructs the schema AS IT WAS immediately BEFORE the first tracked
-- migration (20260612_recurring_walks_rolling_job.sql), so the incremental
-- migrations apply cleanly on top of it. It therefore intentionally OMITS anything
-- the later migrations create/alter, e.g.:
--   * tables conversations, series_decline_feedback, system_messages, private.*
--   * columns bookings.payment_status/window_end_at/…, booking_series.booking_kind,
--     messages.conversation_id, provider_profiles.stripe_*, users.is_admin, …
--   * pets.dob (added later) — baseline keeps the original pets.age_years, which
--     20260615_tru71_pet_dob.sql drops
--   * the series_status value 'pending_meet_greet' (added by 20260615_tru14)
--   * functions/views/policies/triggers that the migrations (re)create
--
-- Generated by reconstructing DDL from the live catalog (pg_get_*def, information_schema).

-- ── Extensions ──────────────────────────────────────────────────────────────
create extension if not exists "uuid-ossp" with schema extensions;
create extension if not exists postgis with schema public;

-- ── Enums ───────────────────────────────────────────────────────────────────
-- 'pending_meet_greet' is intentionally absent; 20260615_tru14 adds it.
create type public.series_frequency as enum ('daily', 'weekdays', 'specific_days');
create type public.series_status as enum ('pending', 'active', 'cancelled', 'completed');

-- ── Pre-existing functions ────────────────────────────────────────────────────
-- (Everything else is (re)created by a later migration via CREATE OR REPLACE.)
create or replace function public.set_updated_at()
returns trigger language plpgsql as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $function$
begin
  insert into public.users (id, auth_id, email, first_name, last_name, role)
  values (
    new.id,
    new.id,
    new.email,
    new.raw_user_meta_data->>'first_name',
    new.raw_user_meta_data->>'last_name',
    coalesce(new.raw_user_meta_data->>'role', 'customer')
  );
  return new;
end;
$function$;

-- Body references public.generate_series_bookings (created later by 20260613); the
-- reference is late-bound (plpgsql) so this is safe to define here.
create or replace function public.trg_series_activated()
returns trigger language plpgsql security definer set search_path to 'public' as $function$
begin
  if new.status = 'active' and (old.status is distinct from 'active') then
    perform public.generate_series_bookings(new.id);
  end if;
  return new;
end;
$function$;

-- ── Tables (FK-dependency order) ──────────────────────────────────────────────

create table public.users (
  id uuid primary key default uuid_generate_v4(),
  auth_id uuid not null,
  email text not null,
  role text not null,
  first_name text not null,
  last_name text not null,
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  avatar_url text,
  constraint users_auth_id_key unique (auth_id),
  constraint users_email_key unique (email),
  constraint users_role_check check (role = any (array['customer'::text, 'provider'::text, 'admin'::text]))
);

create table public.customer_profiles (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.users(id) on delete cascade,
  address text,
  suburb text,
  postcode text,
  emergency_contact text,
  emergency_phone text,
  updated_at timestamptz not null default now(),
  constraint customer_profiles_user_id_key unique (user_id)
);

create table public.provider_profiles (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.users(id) on delete cascade,
  bio text,
  suburb text,
  postcode text,
  location geography(Point,4326),
  radius_km integer not null default 5,
  is_verified boolean not null default false,
  is_active boolean not null default true,
  avg_rating numeric(3,2),
  total_reviews integer not null default 0,
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  abn text,
  experience_years text,
  service_radius_km integer,
  constraint provider_profiles_user_id_key unique (user_id)
);
create index idx_provider_location on public.provider_profiles using gist (location);
create index idx_provider_verified on public.provider_profiles using btree (is_verified, is_active);

create table public.provider_services (
  id uuid primary key default uuid_generate_v4(),
  provider_id uuid not null references public.users(id),
  service_type text not null,
  duration_mins integer,
  price_cents integer,
  description text,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  additional_pet_price_cents integer,
  constraint provider_services_price_cents_nonneg check ((price_cents is null) or (price_cents >= 0)),
  constraint provider_services_provider_service_duration_key unique nulls not distinct (provider_id, service_type, duration_mins)
);
create index provider_services_provider_id_available_idx on public.provider_services using btree (provider_id) where (is_available = true);

create table public.provider_attributes (
  id uuid primary key default uuid_generate_v4(),
  provider_id uuid not null references public.users(id),
  attribute text not null,
  value boolean not null default true,
  created_at timestamptz not null default now(),
  constraint provider_attributes_provider_id_attribute_key unique (provider_id, attribute)
);

create table public.provider_checks (
  id uuid primary key default uuid_generate_v4(),
  provider_id uuid not null references public.provider_profiles(id) on delete cascade,
  check_type text not null,
  status text not null default 'pending'::text,
  document_url text,
  notes text,
  completed_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provider_checks_status_check check (status = any (array['pending'::text, 'approved'::text, 'expired'::text, 'rejected'::text]))
);

create table public.pets (
  id uuid primary key default uuid_generate_v4(),
  customer_id uuid not null references public.customer_profiles(id) on delete cascade,
  name text not null,
  species text not null,
  breed text,
  age_years integer,
  weight_kg numeric(5,2),
  sex text,
  is_desexed boolean,
  microchip_no text,
  vet_name text,
  vet_phone text,
  medical_notes text,
  behaviour_notes text,
  photo_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint pets_species_check check (species = any (array['dog'::text, 'cat'::text, 'other'::text])),
  constraint pets_sex_check check (sex = any (array['male'::text, 'female'::text, 'unknown'::text]))
);

create table public.booking_series (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customer_profiles(id) on delete restrict,
  provider_id uuid not null references public.provider_profiles(id) on delete restrict,
  service_id uuid not null references public.provider_services(id) on delete restrict,
  frequency_type public.series_frequency not null,
  days_of_week integer[] default '{}'::integer[],
  time_of_day time without time zone not null,
  start_date date not null,
  end_date date,
  status public.series_status not null default 'pending'::public.series_status,
  locked_price_cents integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index idx_booking_series_status on public.booking_series using btree (status);

create table public.bookings (
  id uuid primary key default uuid_generate_v4(),
  customer_id uuid not null references public.customer_profiles(id),
  provider_id uuid not null references public.provider_profiles(id),
  pet_id uuid not null references public.pets(id),
  service_id uuid not null references public.provider_services(id),
  status text not null default 'pending'::text,
  scheduled_at timestamptz not null,
  completed_at timestamptz,
  total_cents integer not null,
  customer_notes text,
  provider_notes text,
  rating integer,
  review_text text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  is_meet_and_greet boolean not null default false,
  series_id uuid references public.booking_series(id) on delete set null,
  ends_at timestamptz,
  constraint bookings_status_check check (status = any (array['pending'::text, 'confirmed'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  constraint bookings_rating_check check ((rating >= 1) and (rating <= 5))
);
create index idx_bookings_customer on public.bookings using btree (customer_id, status);
create index idx_bookings_provider on public.bookings using btree (provider_id, status);
create index idx_bookings_scheduled on public.bookings using btree (scheduled_at);
create index idx_bookings_series_id on public.bookings using btree (series_id);

create table public.booking_pets (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  pet_id uuid not null references public.pets(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint booking_pets_booking_id_pet_id_key unique (booking_id, pet_id)
);

create table public.series_pets (
  id uuid primary key default gen_random_uuid(),
  series_id uuid not null references public.booking_series(id) on delete cascade,
  pet_id uuid not null references public.pets(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint series_pets_series_id_pet_id_key unique (series_id, pet_id)
);

-- booking_id is NOT NULL here (pre-conversations); 20260614_tru82 relaxes it to
-- nullable, adds conversation_id, and swaps this FK to ON DELETE SET NULL.
create table public.messages (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  sender_id uuid not null references public.users(id) on delete restrict,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
create index idx_messages_booking_id on public.messages using btree (booking_id);
create index idx_messages_sender_id on public.messages using btree (sender_id);

create table public.notifications (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid not null references public.users(id) on delete cascade,
  booking_id uuid references public.bookings(id) on delete set null,
  type text not null,
  title text not null,
  body text not null,
  is_read boolean not null default false,
  sent_at timestamptz not null default now()
);
create index idx_notifications_user on public.notifications using btree (user_id, is_read, sent_at desc);

create table public.reviews (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings(id) on delete restrict,
  customer_id uuid not null references public.customer_profiles(id) on delete restrict,
  provider_id uuid not null references public.provider_profiles(id) on delete restrict,
  rating integer not null,
  comment text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint reviews_booking_id_key unique (booking_id),
  constraint reviews_rating_check check ((rating >= 1) and (rating <= 5))
);
create index idx_reviews_customer_id on public.reviews using btree (customer_id);
create index idx_reviews_provider_id on public.reviews using btree (provider_id);

create table public.walk_sessions (
  id uuid primary key default uuid_generate_v4(),
  booking_id uuid not null references public.bookings(id) on delete cascade,
  provider_id uuid not null references public.users(id),
  status text not null default 'active'::text,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  distance_metres integer,
  duration_seconds integer,
  created_at timestamptz not null default now(),
  constraint walk_sessions_booking_id_key unique (booking_id),
  constraint walk_sessions_status_check check (status = any (array['active'::text, 'completed'::text, 'cancelled'::text]))
);
create index idx_walk_sessions_booking on public.walk_sessions using btree (booking_id);
create index idx_walk_sessions_status on public.walk_sessions using btree (status);

create table public.walk_updates (
  id uuid primary key default gen_random_uuid(),
  walk_session_id uuid not null references public.walk_sessions(id),
  provider_id uuid not null references public.users(id),
  update_type text not null default 'comment'::text,
  message text,
  photo_url text,
  created_at timestamptz not null default now(),
  constraint walk_updates_update_type_check check (update_type = any (array['comment'::text, 'photo'::text, 'mood'::text]))
);

create table public.gps_pings (
  id uuid primary key default uuid_generate_v4(),
  walk_session_id uuid not null references public.walk_sessions(id) on delete cascade,
  lat numeric(10,7) not null,
  lng numeric(10,7) not null,
  accuracy_metres integer,
  recorded_at timestamptz not null default now()
);
create index idx_gps_pings_session on public.gps_pings using btree (walk_session_id, recorded_at);

-- Pre-existing stub. 20260617_tru125 repurposes it: adds provider_user_id,
-- update_type, tags, has_concern, created_at; sets photo_url NOT NULL + sent_at
-- default; re-adds the booking_id FK. Baseline keeps only the original stub columns.
create table public.booking_updates (
  id uuid primary key default uuid_generate_v4(),
  booking_id uuid not null,
  message text,
  photo_url text,
  sent_at timestamptz not null
);
create index idx_updates_booking on public.booking_updates using btree (booking_id, sent_at);

-- ── Row level security ────────────────────────────────────────────────────────
alter table public.booking_pets enable row level security;
alter table public.booking_series enable row level security;
alter table public.booking_updates enable row level security;
alter table public.bookings enable row level security;
alter table public.customer_profiles enable row level security;
alter table public.gps_pings enable row level security;
alter table public.messages enable row level security;
alter table public.notifications enable row level security;
alter table public.pets enable row level security;
alter table public.provider_attributes enable row level security;
alter table public.provider_checks enable row level security;
alter table public.provider_profiles enable row level security;
alter table public.provider_services enable row level security;
alter table public.reviews enable row level security;
alter table public.series_pets enable row level security;
alter table public.users enable row level security;
alter table public.walk_sessions enable row level security;
alter table public.walk_updates enable row level security;

-- ── Policies (pre-existing only) ──────────────────────────────────────────────
-- messages' original booking_parties_* policies were dropped by 20260614_tru82
-- (which recreates messages_* on top), so they are not reconstructed here.

create policy customers_read_own_booking_pets on public.booking_pets
  for select using (exists (select 1 from public.bookings b join public.customer_profiles cp on cp.id = b.customer_id where b.id = booking_pets.booking_id and cp.user_id = auth.uid()));
create policy providers_read_assigned_booking_pets on public.booking_pets
  for select using (exists (select 1 from public.bookings b join public.provider_profiles pp on pp.id = b.provider_id where b.id = booking_pets.booking_id and pp.user_id = auth.uid()));
create policy customers_insert_own_booking_pets on public.booking_pets
  for insert with check (exists (select 1 from public.bookings b join public.customer_profiles cp on cp.id = b.customer_id where b.id = booking_pets.booking_id and cp.user_id = auth.uid()));

create policy customers_read_own_series on public.booking_series
  for select using (exists (select 1 from public.customer_profiles cp where cp.id = booking_series.customer_id and cp.user_id = auth.uid()));
create policy customers_insert_series on public.booking_series
  for insert with check (exists (select 1 from public.customer_profiles cp where cp.id = booking_series.customer_id and cp.user_id = auth.uid()));
create policy customers_update_own_series on public.booking_series
  for update using (exists (select 1 from public.customer_profiles cp where cp.id = booking_series.customer_id and cp.user_id = auth.uid()));
create policy providers_read_assigned_series on public.booking_series
  for select using (exists (select 1 from public.provider_profiles pp where pp.id = booking_series.provider_id and pp.user_id = auth.uid()));
create policy providers_update_assigned_series on public.booking_series
  for update using (exists (select 1 from public.provider_profiles pp where pp.id = booking_series.provider_id and pp.user_id = auth.uid()));

create policy "Booking parties can view updates" on public.booking_updates
  for select using (booking_id in (select bookings.id from public.bookings
    where bookings.customer_id = (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))
       or bookings.provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))));
create policy "Providers can insert booking updates" on public.booking_updates
  for insert with check (booking_id in (select bookings.id from public.bookings
    where bookings.provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))));

create policy "Customers can view own bookings" on public.bookings
  for select using (customer_id = (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));
create policy "Providers can view own bookings" on public.bookings
  for select using (provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));
create policy "Customers can create bookings" on public.bookings
  for insert with check (customer_id = (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));
create policy "Providers can update own bookings" on public.bookings
  for update using (provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));

create policy "Customers can manage own profile" on public.customer_profiles
  for all using (user_id = (select users.id from public.users where users.auth_id = auth.uid()));
create policy "Users can view their own customer profile" on public.customer_profiles
  for select using (user_id = auth.uid());
create policy "Users can insert their own customer profile" on public.customer_profiles
  for insert with check (user_id = auth.uid());
create policy "Users can update their own customer profile" on public.customer_profiles
  for update using (user_id = auth.uid());

create policy "Booking parties can view gps pings" on public.gps_pings
  for select using (walk_session_id in (select ws.id from public.walk_sessions ws join public.bookings b on b.id = ws.booking_id
    where b.customer_id = (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))
       or b.provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))));
create policy "Customers can view gps pings for their bookings" on public.gps_pings
  for select using (walk_session_id in (select walk_sessions.id from public.walk_sessions where walk_sessions.booking_id in (select bookings.id from public.bookings where bookings.customer_id in (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = auth.uid()))));
create policy "Providers can view own gps pings" on public.gps_pings
  for select using (walk_session_id in (select walk_sessions.id from public.walk_sessions where walk_sessions.provider_id = auth.uid()));
create policy "Providers can create gps pings" on public.gps_pings
  for insert with check (walk_session_id in (select walk_sessions.id from public.walk_sessions where walk_sessions.provider_id = auth.uid()));
create policy "Providers can insert gps pings" on public.gps_pings
  for insert with check (walk_session_id in (select walk_sessions.id from public.walk_sessions where walk_sessions.provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))));

create policy "Users can view own notifications" on public.notifications
  for select using (user_id = (select users.id from public.users where users.auth_id = auth.uid()));
create policy "Users can mark own notifications read" on public.notifications
  for update using (user_id = (select users.id from public.users where users.auth_id = auth.uid()));

create policy "Customers can manage own pets" on public.pets
  for all using (customer_id = (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));
create policy "Users can view their own pets" on public.pets
  for select using (customer_id in (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = auth.uid()));
create policy "Users can insert their own pets" on public.pets
  for insert with check (customer_id in (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = auth.uid()));

create policy "Anyone can view provider attributes" on public.provider_attributes
  for select using (true);
create policy "Providers can manage own attributes" on public.provider_attributes
  for all using (provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));
create policy "Users can view their own attributes" on public.provider_attributes
  for select using (provider_id = auth.uid());
create policy "Users can insert their own attributes" on public.provider_attributes
  for insert with check (provider_id = auth.uid());

create policy "Anyone can view provider checks" on public.provider_checks
  for select using (provider_id in (select provider_profiles.user_id from public.provider_profiles where provider_profiles.is_verified = true));
create policy "Providers can view own checks" on public.provider_checks
  for select using (provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));

create policy "Anyone can view verified providers" on public.provider_profiles
  for select using ((is_verified = true) and (is_active = true));
create policy "Providers can manage own profile" on public.provider_profiles
  for all using (user_id = (select users.id from public.users where users.auth_id = auth.uid()));
create policy "Users can view their own provider profile" on public.provider_profiles
  for select using (user_id = auth.uid());
create policy "Users can insert their own provider profile" on public.provider_profiles
  for insert with check (user_id = auth.uid());
create policy "Users can update their own provider profile" on public.provider_profiles
  for update using (user_id = auth.uid());

create policy "Anyone can view provider services" on public.provider_services
  for select using (is_available = true);
create policy "Users can view their own services" on public.provider_services
  for select using (provider_id = auth.uid());
create policy "Users can insert their own services" on public.provider_services
  for insert with check (provider_id = auth.uid());
create policy "Users can update their own services" on public.provider_services
  for update using (provider_id = auth.uid()) with check (provider_id = auth.uid());
create policy "Users can delete their own services" on public.provider_services
  for delete using (provider_id = auth.uid());

create policy reviews_public_read on public.reviews
  for select using (true);
create policy customers_insert_own_reviews on public.reviews
  for insert with check ((exists (select 1 from public.bookings b join public.customer_profiles cp on cp.id = b.customer_id where b.id = reviews.booking_id and b.status = 'completed'::text and cp.user_id = auth.uid()))
    and (exists (select 1 from public.customer_profiles cp where cp.id = reviews.customer_id and cp.user_id = auth.uid())));
create policy customers_update_own_reviews on public.reviews
  for update using (exists (select 1 from public.customer_profiles cp where cp.id = reviews.customer_id and cp.user_id = auth.uid()));

create policy customers_read_own_series_pets on public.series_pets
  for select using (exists (select 1 from public.booking_series bs join public.customer_profiles cp on cp.id = bs.customer_id where bs.id = series_pets.series_id and cp.user_id = auth.uid()));
create policy customers_insert_series_pets on public.series_pets
  for insert with check (exists (select 1 from public.booking_series bs join public.customer_profiles cp on cp.id = bs.customer_id where bs.id = series_pets.series_id and cp.user_id = auth.uid()));
create policy providers_read_assigned_series_pets on public.series_pets
  for select using (exists (select 1 from public.booking_series bs join public.provider_profiles pp on pp.id = bs.provider_id where bs.id = series_pets.series_id and pp.user_id = auth.uid()));

create policy "Users can read own record" on public.users
  for select using (auth.uid() = auth_id);
create policy "Anyone can view provider users" on public.users
  for select using (role = 'provider'::text);
create policy "Users can update own record" on public.users
  for update using (auth.uid() = auth_id);

create policy "Booking parties can view walk sessions" on public.walk_sessions
  for select using (booking_id in (select bookings.id from public.bookings
    where bookings.customer_id = (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))
       or bookings.provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid()))));
create policy "Customers can view walk sessions for their bookings" on public.walk_sessions
  for select using (booking_id in (select bookings.id from public.bookings where bookings.customer_id in (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = auth.uid())));
create policy "Providers can view own walk sessions" on public.walk_sessions
  for select using (provider_id = auth.uid());
create policy "Providers can manage own walk sessions" on public.walk_sessions
  for all using (provider_id = (select provider_profiles.id from public.provider_profiles where provider_profiles.user_id = (select users.id from public.users where users.auth_id = auth.uid())));
create policy "Providers can create walk sessions" on public.walk_sessions
  for insert with check (provider_id = auth.uid());
create policy "Providers can update own walk sessions" on public.walk_sessions
  for update using (provider_id = auth.uid());

create policy "Customers can view updates for their bookings" on public.walk_updates
  for select using (walk_session_id in (select walk_sessions.id from public.walk_sessions where walk_sessions.booking_id in (select bookings.id from public.bookings where bookings.customer_id in (select customer_profiles.id from public.customer_profiles where customer_profiles.user_id = auth.uid()))));
create policy "Providers can view own walk updates" on public.walk_updates
  for select using (provider_id = auth.uid());
create policy "Providers can create walk updates" on public.walk_updates
  for insert with check (provider_id = auth.uid());

-- ── Triggers (pre-existing only) ──────────────────────────────────────────────
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();
create trigger series_activated after update of status on public.booking_series
  for each row execute function public.trg_series_activated();
create trigger set_booking_series_updated_at before update on public.booking_series
  for each row execute function public.set_updated_at();
create trigger set_reviews_updated_at before update on public.reviews
  for each row execute function public.set_updated_at();

-- ── Views (pre-existing only; definer-style, scoped by auth.uid() in WHERE) ────
create view public.active_walk_view as
  select ws.id as walk_session_id,
    ws.booking_id,
    ws.status,
    ws.started_at,
    ws.distance_metres,
    (select row_to_json(latest.*) from (select gps_pings.lat, gps_pings.lng, gps_pings.recorded_at
        from public.gps_pings where gps_pings.walk_session_id = ws.id
        order by gps_pings.recorded_at desc limit 1) latest) as latest_position,
    (select row_to_json(latest_update.*) from (select booking_updates.message, booking_updates.photo_url, booking_updates.sent_at
        from public.booking_updates where booking_updates.booking_id = ws.booking_id
        order by booking_updates.sent_at desc limit 1) latest_update) as latest_update
  from public.walk_sessions ws
  where ws.status = 'active'::text;

create view public.booking_party_names as
  select b.id as booking_id,
    cu.id as customer_user_id, cu.first_name as customer_first_name, cu.last_name as customer_last_name,
    pu.id as provider_user_id, pu.first_name as provider_first_name, pu.last_name as provider_last_name
  from public.bookings b
    join public.customer_profiles cp on cp.id = b.customer_id
    join public.users cu on cu.id = cp.user_id
    join public.provider_profiles pp on pp.id = b.provider_id
    join public.users pu on pu.id = pp.user_id
  where cp.user_id = auth.uid() or pp.user_id = auth.uid();

create view public.provider_rating_view as
  select provider_id, count(*) as review_count, round(avg(rating), 1) as avg_rating
  from public.reviews group by provider_id;

create view public.provider_search_view as
  select pp.id, pp.user_id, u.first_name, u.last_name, u.avatar_url, pp.bio, pp.suburb, pp.radius_km,
    pp.is_verified, pp.is_active, pp.avg_rating, pp.total_reviews,
    coalesce(json_agg(ps.service_type order by ps.service_type) filter (where ps.service_type is not null), '[]'::json) as services
  from public.provider_profiles pp
    join public.users u on u.id = pp.user_id
    left join public.provider_services ps on ps.provider_id = pp.user_id and ps.is_available = true
  where pp.is_active = true
  group by pp.id, pp.user_id, u.first_name, u.last_name, u.avatar_url, pp.bio, pp.suburb, pp.radius_km, pp.is_verified, pp.is_active, pp.avg_rating, pp.total_reviews;

create view public.series_party_names as
  select bs.id as series_id,
    cu.first_name as customer_first_name, cu.last_name as customer_last_name,
    pu.first_name as provider_first_name, pu.last_name as provider_last_name,
    (select count(*) from public.series_pets sp where sp.series_id = bs.id) as pet_count,
    (select string_agg(p.name, ', '::text order by p.name) from public.series_pets sp join public.pets p on p.id = sp.pet_id where sp.series_id = bs.id) as pet_names
  from public.booking_series bs
    join public.customer_profiles cp on cp.id = bs.customer_id
    join public.users cu on cu.id = cp.user_id
    join public.provider_profiles pp on pp.id = bs.provider_id
    join public.users pu on pu.id = pp.user_id
  where cp.user_id = auth.uid() or pp.user_id = auth.uid();

-- ── Grants (match live: full DML to the PostgREST roles; RLS does the gating) ──
grant all on public.booking_pets, public.booking_series, public.booking_updates,
  public.bookings, public.customer_profiles, public.gps_pings, public.messages,
  public.notifications, public.pets, public.provider_attributes, public.provider_checks,
  public.provider_profiles, public.provider_services, public.reviews, public.series_pets,
  public.users, public.walk_sessions, public.walk_updates,
  public.active_walk_view, public.booking_party_names, public.provider_rating_view,
  public.provider_search_view, public.series_party_names
  to anon, authenticated, service_role;
